server:
    port: 8081
spring:
    application:
        name: AluguelCarros
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://aluguel-cars.cvksisiyyypp.us-east-2.rds.amazonaws.com:3306/aluguel
        username: admin
        password: rootroot
    jpa:
      properties:
          show-sql: true
